### ISSUE TITLE
Input plugins for BVE Trainsim

### ISSUE THREAD

**Issue by saha209** [MarcRiera/ddgo-controller-docs#4]
saha209 (me) did make the plugins depending on some controllers (ps1/ps2/pc).
http://saha209kame.web.fc2.com/BVE_ATSPI.html

**Comment by saha209** [comment]
saha209 also challenge to adapt DenGO controllers to "TRAIN CREW" (train game on unity).
https://store.steampowered.com/app/1618290/TRAIN_CREW_Prologue/?l=japanese
https://twitter.com/saha209_ura/status/1412066867926032384

**Comment by MarcRiera** [comment]
Thank you very much for the information! I have updated the compatibility chart and input plugin section to include references to your work.

I was aware of TRAIN CREW but didn't know it now supported the Type II controller, great job! I will probably add the game to the compatibility chart in the future.
