### ISSUE TITLE
Compatibilidad del mando zuiki de switch con nuevos juegos de PC

### ISSUE THREAD

**Issue by segata4ever** [MarcRiera/ddgo-controller-docs#9]
Hola, primero de todo quiero felicitar al creador por el estupendo trabajo que está haciendo con esta base de datos. 
Expongo la siguiente información por si puede ser de utilidad para ampliar la base de datos: 

- El juego [Hmmsim Metro](https://store.steampowered.com/app/1591420/Hmmsim_Metro/) disponible en Steam se actualizó hace unas semanas e incorporó la posibilidad de jugar con el mando zuiki de forma nativa.
- La versión del juego [Japanese Rail Sim: Operating the MEITETSU Line](https://store.steampowered.com/app/2281540/Japanese_Rail_Sim_Operating_the_MEITETSU_Line/) para Steam también es compatible de forma nativa con el mando zuiki.

**Comment by MarcRiera** [comment]
Hola, me alegro de que la documentación resulte útil. No tenía controlados estos dos juegos, los añadiré a la base de datos en el apartado correspondiente, ¡gracias!
